# Generated by Django 5.0.6 on 2024-06-25 02:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_edit'),
    ]

    operations = [
        migrations.AddField(
            model_name='edit',
            name='firstname',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='edit',
            name='joined_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='edit',
            name='lastname',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='edit',
            name='phone',
            field=models.IntegerField(default=111),
            preserve_default=False,
        ),
    ]
